### ISSUE TITLE
not support appcode 2016.2.1

### ISSUE THREAD

**Issue by zzjf** [JustSid/AppCode-QuickLook#4]
not available in appcode 2016.2.1，any plan for Fixed support for AppCode 2016.2.1?

**Comment by JustSid** [comment]
It works fine for me in AppCode 2016.2.2 EAP, what error is it that you are getting?

**Comment by zzjf** [comment]
Thank for your reply,it may be cause of  Alcatraz.After removing Alcatraz,it works fine in AppCode 2016.2.1.AppCode-QuickLook is very useful to me.

**Comment by JustSid** [comment]
What is Alcatraz? Ideally I would like to make sure that there no incompatibility, but I don't find any JetBrains plugin by that name.

**Comment by zzjf** [comment]
it is a xcode plugin,http://alcatraz.io/.

**Comment by JustSid** [comment]
Interesting, I have a hard time believing that this would interfere with the QuickLook plugin though, since that is completely separate from Xcode.

**Comment by zinets** [comment]
hi; your cool plugin stopped work for me a few month ago (after updating AppCode to 2017.* i believe) and it's very sad. I use latest AppCode (2017.2.3)

there is log; any solutions?

While loading class com.widerwille.quicklook.QuickLookFullValueEvaluator$1: class com.widerwille.quicklook.QuickLookFullValueEvaluator$1 has interface com.jetbrains.cidr.execution.debugger.CidrDebugProcess$DebuggerCommand as super class [Plugin: com.widerwille.quicklook]
com.intellij.diagnostic.PluginException: While loading class com.widerwille.quicklook.QuickLookFullValueEvaluator$1: class com.widerwille.quicklook.QuickLookFullValueEvaluator$1 has interface com.jetbrains.cidr.execution.debugger.CidrDebugProcess$DebuggerCommand as super class [Plugin: com.widerwille.quicklook]
   at com.intellij.ide.plugins.cl.PluginClassLoader.a(PluginClassLoader.java:141)
   at com.intellij.ide.plugins.cl.PluginClassLoader.a(PluginClassLoader.java:76)
   at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:63)
   at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
   at com.widerwille.quicklook.QuickLookFullValueEvaluator.startEvaluation(QuickLookFullValueEvaluator.java:36)
   at com.intellij.xdebugger.impl.ui.tree.nodes.HeadlessValueEvaluationCallback.startFetchingValue(HeadlessValueEvaluationCallback.java:31)
   at com.intellij.xdebugger.impl.ui.tree.nodes.XValueNodeImpl$2.onClick(XValueNodeImpl.java:244)
   at com.intellij.xdebugger.impl.ui.tree.XDebuggerTree$4.handleTagClick(XDebuggerTree.java:175)
   at com.intellij.openapi.vcs.changes.issueLinks.LinkMouseListenerBase.onClick(LinkMouseListenerBase.java:60)
   at com.intellij.ui.ClickListener$1.mouseReleased(ClickListener.java:73)
   at com.intellij.openapi.wm.impl.IdeGlassPaneImpl.a(IdeGlassPaneImpl.java:432)
   at com.intellij.openapi.wm.impl.IdeGlassPaneImpl.dispatch(IdeGlassPaneImpl.java:238)
   at com.intellij.ide.IdeEventQueue.h(IdeEventQueue.java:655)
   at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:608)
   at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
   at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
   at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
   at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
   at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
   at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
   at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.IncompatibleClassChangeError: class com.widerwille.quicklook.QuickLookFullValueEvaluator$1 has interface com.jetbrains.cidr.execution.debugger.CidrDebugProcess$DebuggerCommand as super class
   at java.lang.ClassLoader.defineClass1(Native Method)
   at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
   at java.lang.ClassLoader.defineClass(ClassLoader.java:642)
   at com.intellij.util.lang.UrlClassLoader._defineClass(UrlClassLoader.java:272)
   at com.intellij.util.lang.UrlClassLoader.defineClass(UrlClassLoader.java:268)
   at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:237)
   at com.intellij.ide.plugins.cl.PluginClassLoader.a(PluginClassLoader.java:138)
   ... 20 more
